# -*- coding: utf-8 -*-
"""AI_Agent_AI뉴스요약.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trPy_I5Xvlv_uzqVtPiaz1SFbcjh5evL
"""

import os
import feedparser
import requests
from openai import OpenAI

# 설정

AI_NEWS_RSS = "https://news.google.com/rss/search?q=AIOR인공지능ORLLMOR생성형AIORChatGPT&hl=ko&gl=KR&ceid=KR:ko"

OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
DISCORD_WEBHOOK_URL = os.environ["DISCORD_WEBHOOK_URL"]

if not OPENAI_API_KEY:
    raise ValueError("OPENAI_API_KEY가 없습니다.")

if not DISCORD_WEBHOOK_URL:
    raise ValueError("DISCORD_WEBHOOK_URL이 없습니다.")

client = OpenAI(api_key=OPENAI_API_KEY)

# 뉴스 가져오기
def fetch_top_news(rss_url, max_items=10):
  feed = feedparser.parse(rss_url)

  articles = []
  for entry in feed.entries[:max_items]:
    articles.append(entry.get("title",""))

  return articles

#뉴스 요약
def summarize_news(articles):
  news_text = "\n".join(
      [f"{i+1}. {title}" for i, title in enumerate(articles)]
  )

  prompt = f"""
아래는 오늘의 AI 뉴스 제목이다.

{news_text}

다음 형식으로 한국어로 요약해라.

1. 오늘의 핵심 AI 뉴스 5개
2. 왜 중요한가
3. 취업 준비생 관점 메모

짧고 명확하게 작성하라.
"""

  response = client.responses.create(
      model = "gpt-4o",
      input = prompt
  )

  return response.output_text

#디스코드 전송

def send_to_discord(message):
    safe_message = message[:1900]  # 디스코드 길이 제한 대비

    response = requests.post(
        DISCORD_WEBHOOK_URL,
        json={"content": safe_message},
        timeout=20,
    )

    print("디스코드 전송 상태코드:", response.status_code)
    print("디스코드 응답:", response.text)

    response.raise_for_status()

#실행
def main():
    print("웹훅 존재 여부:", DISCORD_WEBHOOK_URL is not None)

    articles = fetch_top_news(AI_NEWS_RSS)
    print("가져온 뉴스 개수:", len(articles))
    print("뉴스 샘플:", articles[:3])

    summary = summarize_news(articles)
    print("요약 결과 일부:", summary[:300])

    message = f"📢 오늘의 AI 뉴스 브리핑\n\n{summary}"
    send_to_discord(message)


if __name__ == "__main__":
    main()

